### ISSUE TITLE
Chrome crashing without any reason

### ISSUE THREAD

**Issue by MIcQo** [The-West-Scripts/TW-Calc-Script#47]
**Describe the bug**
Something weird happen this week, after load extension, Chrome crashes without any error, message or something like this.
After disabling this script, crashes stopped.

**To Reproduce**
I don't know, after update to latest version it's weird.
After disabling this script, crashes stopped.

**Expected behavior**
Should not crashing.

**Screenshots**
No.

**Environment (please complete the following information):**
Chrome 88.0.4324.192
TWCalc 2.0.6

**Comment by timzatko** [comment]
Hi!

1. Do you use the tampermonkey, or other user script handler?
2. Does it crash immediately after loading the script (game)?
